# Generated by Django 5.0.6 on 2024-05-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scrollmodel',
            options={'verbose_name': 'Discounted Product', 'verbose_name_plural': 'Discounted Products'},
        ),
        migrations.AddField(
            model_name='scrollmodel',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scrollmodel',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='discounted_food'),
        ),
    ]
