# Generated by Django 5.0.6 on 2024-05-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationsmodel',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
